- package.json
- src/components/Sidebar/index.tsx
- src/components/Tooltip/index.tsx
- src/constants/data.ts
- src/containers/Editor/Tools.tsx
- src/containers/JsonEditor/index.tsx
- src/reducer/reducer.ts
- src/typings/global.ts
- yarn.lock
* Updated sidebar icons
* Updated Tools bar above graph
* Removed autoformat from sidebar
* Sidebar width reduced from 42px to 36px
Export layout in `.png` format. An example of image shown below:
Resolves #11
> Export Graph As Image

- package.json
- src/components/CustomNode/ObjectNode.tsx
- src/components/CustomNode/TextNode.tsx
- src/components/CustomNode/index.tsx
- src/components/GoogleAnalytics/index.tsx
- src/components/Graph/index.tsx
- yarn.lock
* Used "react-render-if-visible" package to optmize rendering of graph. Node datas out of viewport are now invisible to prevent DOM Tree overload.
Solves #25
> Optimize Rendering Performance

- src/components/Sponsors/index.tsx
I am experiencing an issue visiting the page jsonvisio.com using firefox developer edition 104.0b6. It appears the initialization to display the sponsors.users array on useConfig.tsx introduced on commit `ae667d4a3b6db200055bfd5401c704aef39784f5` with message log `add sponsors section` is failing for this firefox edition. This is the screenshot.
Error log on console:
```
TypeError: can't access property "length", e.users is undefined
NextJS 10
_app-386553644f916d14.js:1:29310
```
```
TypeError: can't access property "length", e.users is undefined
NextJS 10
_app-386553644f916d14.js:1:29310
```
I copied only the relevant error messages. When reproducing on my local main branch, I found the error was on the line I'm changing on this commit.
After creating this patch, I visited jsonvisio.com …
> fix: added nullsafe operator to patch home error

- Dockerfile
- README.md
- default.conf
Slightly improved version of #72
> New dockerfile

- src/components/CustomNode/TextNode.tsx
- src/components/CustomNode/styles.tsx
- src/components/Graph/index.tsx
- src/containers/Editor/LiveEditor/helpers.ts
- src/containers/Editor/NodeTools.ts
- src/containers/Editor/Tools.tsx
- src/hooks/store/useNodeTools.tsx
- src/utils/findEdgeChildren.ts
- src/utils/findNodeChildren.ts
I see this issue #2 then I [implemented](https://jsonvisio-3gk3406wo-victor-brambati.vercel.app/editor) a node that can collapse, expand the nodes collapsed and restart all nodes collapsed. I created a node tools in tools but I need help to improve UI/UX of this.
> Add Collapse Nodes

- src/components/Graph/index.tsx
When I collapse a node of id from 1 to 10 in a big json the others nodes is hidden. if I collapse id 3, will be collapsed ids, 30, 31, 32... 300. It is because that selector `id*=` select all that includes in beginning or end, But if use the selector `id$=` will only select the end of the`id=`. To know more click [here](https://stackoverflow.com/a/56328426/19669907).
> fix hide wrong collapsed nodes

- src/components/Button/index.tsx
- src/components/ErrorContainer/ErrorContainer.tsx
- src/components/Graph/index.tsx
- src/components/Modal/styles.tsx
- src/components/Sidebar/index.tsx
- src/components/Tooltip/index.tsx
- src/constants/data.ts
- src/constants/globalStyle.ts
- src/constants/theme.ts
- src/containers/Editor/JsonEditor/index.tsx
- src/containers/Editor/Tools.tsx
- src/containers/Modals/NodeModal/index.tsx
- src/containers/Modals/SettingsModal/index.tsx
- src/hooks/store/useConfig.tsx
- src/hooks/store/useStored.tsx
- src/hooks/useFocusNode.tsx
- src/pages/Widget/index.tsx
- src/typings/styled.d.ts
Design improvements made with considerations of #120 
* Moved theme change to settings modal
* Removed borders from sidebar buttons
* Add dotted background to graph
* Set `Node Content` data to "readOnly"
* Add Download Button to mobile view
* Improve general element a11y and W3C
> General UI/UX Improvements

- README.md
Right now, clicking on the Travis CI badge just opens the image itself.
With this change, it links to the current build status dashboard, which
is much more useful.
> Link Travis CI badge to project build status

- README.md
* convert code block into Markdown for readability
* add link to the Dockerfile for easy reference
> Update Docker section formatting in README

- src/components/CustomNode/ObjectNode.tsx
- src/components/CustomNode/TextNode.tsx
- src/components/CustomNode/index.tsx
* Memoized nodes to prevent avoid re-renders on JSON update
> Improve Editor Rerender Performance

- src/components/CustomNode/styles.tsx
#164 
1. `box-sizing: border-box;`
remain the <foreignObject/> height 40px (border-2px * 2, content 36px)
2. set height fixed `18px`; `padding:7px;`
36px  (2*2 + 7*2 + 18)
> fix: highlight red-dashed border display

- package.json
- src/components/MonacoEditor/index.tsx
- src/pages/Widget/index.tsx
- src/typings/types.d.ts
- src/utils/isValidJson.ts
- src/utils/jsonParser.ts
- yarn.lock
Implements #145 ... Kind of.
This implementation strips JSONC, therefore converting it to plain JSON.
It does that by using Microsoft's ['jsonc-parser'](https://www.npmjs.com/package/jsonc-parser) package.
Inputting any JSONC data will result in the comments getting stripped and the user being greeted by a warning toast notification.
> Accept JSONC by stripping it of it's comments

- src/components/CustomNode/TextNode.tsx
- src/components/CustomNode/index.tsx
- src/components/CustomNode/styles.tsx
- src/containers/Modals/SettingsModal/index.tsx
- src/hooks/store/useStored.tsx
- src/typings/types.d.ts
- src/utils/jsonParser.ts
Implements #169
- Adds children count label next to text node key
- Adds option to toggle visibility of children count label
> Added children count label next to the node key

- src/components/Sidebar/index.tsx
- src/hooks/store/useGraph.tsx
Solves #188
This PR implements a Expand/Collapse Graph button in the sidebar that does exactly what the name implies.
https://user-images.githubusercontent.com/71708164/194066587-10436847-6613-4798-8a87-8f86519692a3.mov
> Added a 'Collapse/Expand Graph' button

- src/hooks/store/useGraph.tsx
resolves #241 
- expand nodes that are already collapsed and directly connected to parent node.
> Fix: don't show disconnected nodes on expand

- src/utils/getOutgoers.ts
- src/utils/jsonParser.ts
I created the PR #242 but the updates created a conflict with my old PR. This PR solve the same problem, I tested the problems from #242 and it work correctly. Thank you for the patience.
> fix empty nodes

- src/components/CustomNode/TextNode.tsx
- src/components/CustomNode/styles.tsx
- src/constants/theme.ts
- src/typings/styled.d.ts
- src/utils/jsonParser.ts
> seperate colors from array and object

- src/containers/Modals/ImportModal/index.tsx
Add a feature that import file by drag and drop.
https://user-images.githubusercontent.com/71168966/210169418-a10c4389-3f42-40cb-903e-5ccb5fa63f4a.mov
Solve the issue #283
> import file by drag and drop

- src/components/Graph/CustomNode/TextNode.tsx
Fixes #345
- The TextNode component is not being re-rendered when the 'childrenCount' is updating.
- Added the condition that when it changes, it should re-render the component 
- Changes are made in the propsAreEqual function.
https://github.com/AykutSarac/jsoncrack.com/assets/74180320/2010cf3e-50f9-4748-a440-824e321e0c6f
> Fixed array length doesn't update

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
Updated 
- Dockerfile for cache
- README.md based the new conf
Created
- .gitignore - to ignore the non docker file 
- docker-compose.yml - conf as file along with the image build and run at a time with docker-compose up -d
> Dockefile conf updated cache. Created other conf for dockerisation.

- src/layout/Footer/index.tsx
changed  "Twitter" to "𝕏 (Twitter)" 
This fixes https://github.com/AykutSarac/jsoncrack.com/issues/362
> fix: changed  "Twitter" to "𝕏 (Twitter)"

- src/containers/Views/GraphView/index.tsx
- src/store/useGraph.ts
**### Issue**:
This pull request addresses the issue where the zoom label next to the zoom dropdown and input field does not update to reflect the selected zoom level (Issue #388 ).
This PR implements a fix that ensures the zoom label accurately displays the chosen zoom level, regardless of whether it's selected from the dropdown or entered in the input field.
Added a code block that dynamically updates the viewport in real-time as the user adjusts the zoom level. 
Because we are displaying the zoomFactor propery of viewport in the zoom label which was not updating
This enhancement ensures immediate synchronization between the user's zoom actions and the displayed viewport. Prior to this update, the viewport did not reflect changes in zoom levels promptly, resulting in the display of …
> fix: Zoom label not updating on selection/input

- README.md
The command `pnpm` is incorrect. Instead it must be `pnpm install` to install the dependencies of the project.
> Incorrect Installation Command

- Dockerfile
Fix :: build docker image with /bin/sh: pnpm: not found
```
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
```
> Fix :: build docker image with /bin/sh: pnpm: not found

- README.md
This PR adds a direct hyperlink to the `LICENSE` file in the `README.md` to improve accessibility and user experience.
- The `README.md` references the `LICENSE` file but does not provide a direct link.
- Users who want to view the licensing terms must navigate manually to the `LICENSE` file in the repository.
- This can be inconvenient and may deter users from reviewing the license information.
- Added a hyperlink to the `LICENSE` file in the `README.md`.
- This allows users to access the license information with a single click directly from the `README`.
- Enhances documentation usability.
- No changes to code or functionality.
- Improves transparency regarding licensing terms.
- Clicked the new `LICENSE` link in the `README.md` to ensure it correctly redirects to the `LICENSE` file.
- …
> Add hyperlink to LICENSE file in README

- src/pages/404.tsx
- src/pages/_error.tsx
Hello,
2 pages are named after "ToDiagram" when I assume that in this repo they should be named after "JSON Crack"
> fix typo in error pages' title

- Dockerfile
Thank you for creating such a great tool!
Two minor changes:
- Changed the base Docker image for the `production` stage to `nginx-unprivileged` for better security (i.e., does not run as `root`)
- Added the `nginxinc` namespace to remove ambiguity and ensure the official `nginx` image is used
- Fixed the exposed port in the `Dockerfile` to match the listening port in `nginx.conf`
> Use nginx-unprivileged image; fix exposed port

- src/features/editor/TextEditor.tsx
Hello,
Should the version follow here the one defined there ?https://github.com/AykutSarac/jsoncrack.com/blob/46d1182a5d59f7a657de6cb2035bb5926c270afb/pnpm-lock.yaml#L25
> upgrade cdnjs link for monaco-editor to 0.52.2
